# name of your github action
name: CI
# this will help you specify where to run 
on:
  push:
    branches:
    # run on the main branch
     - main
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - uses: actions/setup-node@master
      with:
        node-version: 17.3
    - name: see directory
      run: ls
    - name: Install dependencies
      run: yarn install
    - name: Build on MacOS
      run: yarn run dist -p onTagOrDraft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: electron-builder
    - name: see directory in dist
      run: ls -l ./dist
    - uses: actions/upload-artifact@v3
      with:
        name: my-macos-artifact
        path: dist/shoebox*.dmg
  
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - uses: actions/setup-node@master
      with:
        node-version: 17.3
    - name: see directory
      run: ls
    - name: Install dependencies
      run: yarn install
    - name: Build on linux
      run: yarn run dist -p onTagOrDraft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: electron-builder
    - name: see directory in dist
      run: ls -l ./dist
    - uses: actions/upload-artifact@v3
      with:
        name: my-linux-artifact
        path: dist/shoebox*AppImage
    # - name: Upload the artifacts
    #     uses: skx/github-action-publish-binaries@master
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       args: 'dist/shoebox*AppImage'
  
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main        
    - uses: actions/setup-node@master
      with:
        node-version: 17.3
    # - name: install node tools
    #   run: yarn global add windows-build-tools
    # - name: install node-gyp
    #   run: yarn global add node-gyp
    - name: Install dependencies
      run: yarn install
    - name: Build on Windows
      run: yarn run dist -p onTagOrDraft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: electron-builder
    - name: see directory
      run: ls ./dist
    - uses: actions/upload-artifact@v3
      with:
        name: my-windows-artifact
        path: dist/shoebox*.exe
