name: release

# Run on every commit tag which begines with "v*" (e.g. v1.3.0)
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on:
      name: "Release"
      runs-on: "ubuntu-latest"
      steps:
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo-token: "${{ secrets.GITHUB_TOKEN" }}"
            prerelease: false